apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: appsody-hello-world-nodejs
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: index.docker.io/kvijai/nodejs-image
            imagePullPolicy: Always
            ports:
            - containerPort: 9080
